name: learnu actions pipeline
on: 
  push:
    branches: [master]
jobs:
  deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Deploy Learnu App
         uses: appleboy/ssh-action@v0.1.2
         with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{seecrets.SSH_USERNAME}}

          script: |
            mkdir test
            cd test