name: learnu actions pipeline
on: 
  push:
    branches: [master]
jobs:
  deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Deploy Learnu App
         uses: appleboy/ssh-action@v0.1.2
         with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |            
            cd test            
            cd learnu/www
            $echo ${{secrets.PASSWORD}} | sudo -S cp index.html /var/www/html/index.html